//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DirectXDrawing.rc
//
#define IDD_DIRECTXDRAWING_DIALOG       102
#define IDD_OLE_PROPPAGE_ZOOM_TAB       105
#define IDD_OLE_PROPPAGE_INTENSITY_TAB  106
#define IDD_OLE_PROPPAGE_COLOR_TAB      107
#define IDD_OLE_PROPPAGE_REARRANGE_TAB  108
#define IDD_OLE_PROPPAGE_NETWORK_TAB    109
#define IDD_OLE_PROPPAGE_DIRECTX        110
#define IDR_MAINFRAME                   128
#define IDB_CIRCLE                      137
#define IDB_ELLIPSE                     138
#define IDB_LINE                        139
#define IDB_OPEN_POLYGON                140
#define IDB_POLYGON                     141
#define IDB_BITMAP6                     142
#define IDB_ZOOM_IN                     144
#define IDB_ZOOM_OUT                    145
#define IDB_BRING_TO_FRONT              146
#define IDB_SEND_TO_BACK                147
#define IDC_STATIC_RENDER_AREA          1000
#define IDC_GROUP_TOOLBOX               1001
#define IDC_GROUP_RIGHT_CLICK_LOCATION  1002
#define IDC_RADIO_ELLIPSE               1003
#define IDC_TAB_OPTIONS                 1004
#define IDC_BUTTON_ZOOM_IN              1005
#define IDC_GROUP_MOUSE_LOCATION        1005
#define IDC_BUTTON_ZOOM_OUT             1006
#define IDC_GROUP_LEFT_CLICK_LOCATION   1006
#define IDC_STATIC_ZOOM_TAB_TITLE       1007
#define IDC_GROUP_OTHER_OPTIONS         1007
#define IDC_RADIO_RECTANGLE             1008
#define IDC_RADIO_LINE                  1009
#define IDC_RADIO__FILLED_ELLIPSE       1010
#define IDC_RADIO_FILLED_RECTANGLE      1011
#define IDC_STATIC_OPACITY              1012
#define IDC_STATIC_SELECTED_INTENTSITY  1013
#define IDC_STATIC_SELECTED_OPACITY     1014
#define IDC_BUTTON_SEND_TO_BACK         1015
#define IDC_STATIC_FILL_COLOR_PICKER    1016
#define IDC_STATIC_NETWORK_TAB_TITLE    1017
#define IDC_STATIC_MESSAGE              1018
#define IDC_BUTTON_SEND                 1019
#define IDC_BUTTON_BRING_TO_FRONT       1020
#define IDC_EDIT_MESSAGE                1021
#define IDC_STATIC_OUTLINE_COLOR_PICKER 1022
#define IDC_RADIO_HOOK                  1022
#define IDC_STATIC_REARRANGE_TAB_TITLE  1023
#define IDC_STATIC_MOUSE_LOCATION_X_LABEL 1023
#define IDC_MFCCOLORBUTTON_FILL         1024
#define IDC_STATIC_MOUSE_LOCATION_Y_LABEL 1024
#define IDC_STATIC_LEFT_CLICK_LOCATION_X_LABEL2 1025
#define IDC_STATIC_LEFT_CLICK_LOCATION_X_LABEL 1025
#define IDC_RADIO_PLOYGON               1026
#define IDC_RADIO_POLYGON               1026
#define IDC_STATIC_INTENSITY            1027
#define IDC_STATIC_LEFT_CLICK_LOCATION_Y_LABEL2 1027
#define IDC_STATIC_LEFT_CLICK_LOCATION_Y_LABEL 1027
#define IDC_SLIDER_INTENSITY            1028
#define IDC_STATIC_RIGHT_CLICK_LOCATION_X_LABEL3 1028
#define IDC_STATIC_RIGHT_CLICK_LOCATION_X_LABEL 1028
#define IDC_STATIC_INTENSITY_TAB_TITLE  1029
#define IDC_STATIC_RIGHT_CLICK_LOCATION_Y_LABEL3 1029
#define IDC_STATIC_RIGHT_CLICK_LOCATION_Y 1029
#define IDC_STATIC_RIGHT_CLICK_LOCATION_Y_LABEL 1029
#define IDC_STATIC_COLOR_OPTIONS        1030
#define IDC_STATIC_MOUSE_LOCATION_X     1030
#define IDC_MFCCOLORBUTTON_OUTLINE      1031
#define IDC_STATIC_MOUSE_LOCATION_Y     1031
#define IDC_SLIDER_OPACITY              1032
#define IDC_STATIC_LEFT_CLICK_LOCATION_X 1032
#define IDC_RADIO__CIRCLE               1033
#define IDC_RADIO_CIRCLE                1033
#define IDC_RADIO_OPEN_POLYGON          1034
#define IDC_GROUPBOX_COLOR              1035
#define IDC_RADIO_UN_FILLED             1036
#define IDC_RADIO_FILLED                1037
#define IDB_RECTANGLE                   1038
#define IDC_STATIC_LEFT_CLICK_LOCATION_Y 1038
#define IDC_STATIC_RIGHT_CLICK_LOCATION_X 1039
#define IDC_STATIC_RIGHT_LOCATION_LOCATION_Y 1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1043
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
